# \ub370\uc774\ud130\ubca0\uc774\uc2a4 \uc124\uc815 yaml\uc774 \uc880\ub354 \ud3b8\ub9ac
spring :
  datasource:
    dirver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dw_501
    username: root
    password: Wkwmdsk18!
  jpa:
   database: mysql
   generate-ddl: true
   hibernate.ddl.auto: update
   show-sql: true
